FROM golang:1.25.1-trixie

RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y \
        make \
        xz-utils \
        zip unzip \
        gcc-mingw-w64 \
        netcat-traditional \
        xxd && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/upx/upx/releases/download/v5.0.1/upx-5.0.1-amd64_linux.tar.xz && \
    tar pxfv upx-5.0.1-amd64_linux.tar.xz -C /bin upx-5.0.1-amd64_linux/upx --strip-components 1 && \
    rm upx-5.0.1-amd64_linux.tar.xz

RUN go install mvdan.cc/garble@v0.15.0

WORKDIR /app
RUN mkdir /data

COPY build_netrc /root/.netrc
COPY backend_linux_amd64 backend_linux_amd64
COPY ./ ./
ENV GOPROXY=http://goproxy.dev-go-red.xyz,direct
RUN go mod download

CMD ["./backend_linux_amd64"]
